### ISSUE TITLE
Far Cry 5

### ISSUE THREAD

**Issue by Folkmancer** [linzhouyu/ACST#10]
Is it possible to work with saves for Far Cry 5?

**Comment by linzhouyu** [comment]
Unfortunately FC5 saves are not supported as for now.

**Comment by Folkmancer** [comment]
Maybe you can help with the processing save algorithm?

**Comment by linzhouyu** [comment]
The encryption pattern for FC5 is quite different from other titles. It's
not possible to process those saves at this moment.
