### ISSUE TITLE
Failed to load save (Valhalla save from Stadia)

### ISSUE THREAD

**Issue by unsuccessfully** [linzhouyu/ACST#105]
I have 60+ hours on AC: Valhalla through Stadia which was linked to a different Ubisoft account than the one I purchased the game on. I've tried troubleshooting this myself for hours and I'm not sure what to do from here. Can you help me transfer my save file between Ubisoft accounts?
[Local Test Saves.zip](https://github.com/linuslin0/ACST/files/10211489/Local.Test.Saves.zip)
[Stadia Saves.zip](https://github.com/linuslin0/ACST/files/10211490/Stadia.Saves.zip)

**Comment by unsuccessfully** [comment]
Nevermind. I caved and was able to get a copy of the save from Ubisoft that worked fine with the tool. Thanks!

**Comment by linuslin0** [comment]
Glad it worked for you. If possible, could you please share the save you got from the Ubisoft, assuming it matches whatever you have on the Stadia? Thanks.
Also, Valhalla seems support cross platform saves, if that works I believe there is no need to even use this tool. We should be able to download the cloud save in the game directly.

**Comment by unsuccessfully** [comment]
The Stadia save didn't appear in my local copy of Valhalla. I didn't even try to see if the Ubisoft save appeared without running it through the tool first...

Here's the Ubisoft files that are the same save as the Stadia files. Hope this helps!
[bd6fda28-2a52-4e36-bed4-6461cba0829e.zip](https://github.com/linuslin0/ACST/files/10220544/bd6fda28-2a52-4e36-bed4-6461cba0829e.zip)

**Comment by linuslin0** [comment]
Thanks, Stadia save seems not compatible with the PC version of this game. Same with AC Odyssey.
