### ISSUE TITLE
Game crash when loading the save (AC:Odyssey)

### ISSUE THREAD

**Issue by YaPoNeC** [linzhouyu/ACST#11]
Hello, first of all, thanks for this great tool.

I am able to convert AC:Odyssey saves without any problem and the game is recognizing them as legit saves, but the game crashes every time during the loading of the saved game.

I have tried to convert many different saves, even the 100% ones on the internet, but there's a crash everytime.

Do you by any chance have encountered this problem?
Thank you very much again

**Comment by linzhouyu** [comment]
Please make sure you were not trying to load a save from a higher version
of this game, that won't work.
If you can already see the converted save entry in the game, then ACST
already did its job. If you want, shot me an email with those saves, I
could help to verify if they could be loaded here. Thanks.

**Comment by linzhouyu** [comment]
Note: Issue caused by corrupted game data file.
