### ISSUE TITLE
Cant convert my file

### ISSUE THREAD

**Issue by CastroManuel** [linzhouyu/ACST#12]
Hi, i was trying to convert my ac4 files to a legit version but it keeps telling me that the it "failed to load save". I dont know what i could be doing wrong

**Comment by linzhouyu** [comment]
Hi there,
ACST by default only supports saves from legit games. If you want to convert your non-standard saves to legit, feel free to shot me an email with the saves you want to convert, and a test save from your legit game copy.

**Comment by linzhouyu** [comment]
Note: Issue resolved my email.
