### ISSUE TITLE
[AC: Revelations] Damaged save game after conversion/decryption

### ISSUE THREAD

**Issue by techurious** [linzhouyu/ACST#17]
I tried using this software to share my Revelations savegame with a friend, and no matter what we try, the game doesn't recognize the data. We used correct legacy usernames for decryption/encryption. The decryption process doesn't indicate any errors (Done). Yet the game doesn't recognize both decrypted save files and decrypted/encrypted save files. Non of the save data works (1.save or 2.save). Also, I can't separately encrypt the save file if it's already been decrypted ("Invalid decryption key" error).
If it matters, I have a Uplay version of a game, and his game is on Steam.

**Comment by linzhouyu** [comment]
Hi there,
Please make sure to use the lower case of the legacy username for encryption/decryption ID. Also, only 2.save is encrypted, don't need to touch 1.save.

**Comment by techurious** [comment]
Turns out that was the problem as I was using both upper and lower case. However, I suggest adding this key information to README as this requirement wasn't obvious enough in the instruction. Thanks!

**Comment by linzhouyu** [comment]
Np, glad it worked. README updated accordingly.
