### ISSUE TITLE
打开应用报错7z SFX error

### ISSUE THREAD

**Issue by hewz** [linzhouyu/ACST#18]
应用版本：v2.3.1
操作系统：Win10 1809
![捕获](https://user-images.githubusercontent.com/3361000/69844865-f906ce80-12a8-11ea-81ba-3fbae6eac820.PNG)

**Comment by linzhouyu** [comment]
这个应该是7z sfx打包模块的问题，请用7zip或者类似软件直接解压ACSaveTool_x64.exe文件，运行其中的ACST\ACSaveTool.exe
