### ISSUE TITLE
how to find converted files?

### ISSUE THREAD

**Issue by NotBrendan** [linzhouyu/ACST#19]
How do I find the  (*.save)  or converted files?

I first opened the save files I wanted to bring over to the legit version. then did the re-selection got the encryption id and then I do the convert. But where do I get it to copy it to the legit version.

**Comment by linzhouyu** [comment]
It's a in-place conversion on the file you choose load, original file would be backed up in acst_backup folder.

**Comment by NotBrendan** [comment]
looks like the game does not detect the save file

**Comment by NotBrendan** [comment]
-> D:\Games\Assassins Creed Odyssey\Saves\CPY_SAVES\Brendan\UPLAY\5059\27.save

-> Processing "27.save" ... 
Game title: Assassin's Creed Odyssey
Save info: ACOd[ManualSave19]-tm_2018_11_12_17_01_41
... Done.

Execution time: 0.0217004

**Comment by linzhouyu** [comment]
Did you put the converted 27.save into your Uplay save location?

**Comment by NotBrendan** [comment]
Yes. C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\savegames\(my ID)\5092

**Comment by linzhouyu** [comment]
If you already disabled the cloud save sync, then likely the encryption id is wrong in your case. Make sure you used a test save from your Uplay account for this game to detect the encryption id, or just put your account GUID as the encryption id.
