### ISSUE TITLE
Stadia Saves?

### ISSUE THREAD

**Issue by jetdotnet** [linzhouyu/ACST#20]
I was recently able to pull my stadia saves down and was hoping to convert them to work locally. The files look to be about the right size and I found what I believe would be my decryption id but no luck.

Any chance your interested in updating this to work with save files from Stadia as well?

**Comment by linzhouyu** [comment]
Hi, if you don't mind, please share the save from Stadia through email.
Thanks.

**Comment by linzhouyu** [comment]
Based on the tests, Stadia saves (even converted) cannot be loaded by the local version of ACD.

**Comment by Technifocal** [comment]
Hi @linuslin0, now that Stadia is shutting down I'm interested in what specifically makes then unable to be loaded by the native Windows version?

I understand this is `wontfix` though.

**Comment by linuslin0** [comment]
@Technifocal This tool doesn't modify actual save data. Stadia might use a special build of the game that its save won't be able to load by normal PC version.

**Comment by Technifocal** [comment]
Understood @linuslin0, how did you get the decryption key for the Stadia save? Or was the whole (encrypted) save different?

**Comment by linuslin0** [comment]
> Understood @linuslin0, how did you get the decryption key for the Stadia save? Or was the whole (encrypted) save different?

Stadia saves are not encrypted.
