### ISSUE TITLE
I can't convert AC: Rogue save to my Uplay AC: Rouge Asia Region. Also no game key!

### ISSUE THREAD

**Issue by PhinnTH** [linzhouyu/ACST#21]
As the topic. I've converted successed. But I found corrupted save game! I play Assassin's Creed Rogue by using Uplay Client. Not Steam Client. I know that There's no Game Key in Uplay Launcher!
![Screenshot (68)](https://user-images.githubusercontent.com/38722732/78133402-9422d700-7448-11ea-8551-90a276b7a037.png)
Here's that AC: Rogue ownership of Uplay DRM. I don't have key due to I bought from Ubisoft Store at all!

**Comment by PhinnTH** [comment]
> 
> 
> As the topic. I've converted successed. But I found corrupted save game! I play Assassin's Creed Rogue by using Uplay Client. Not Steam Client. I know that There's no Game Key in Uplay Launcher!
> ![Screenshot (68)](https://user-images.githubusercontent.com/38722732/78133402-9422d700-7448-11ea-8551-90a276b7a037.png)
> Here's that AC: Rogue ownership of Uplay DRM. I don't have key due to I bought from Ubisoft Store at all!

Oh-oh! Sorry that I'm too busy to reply. I'm active until bedtime.

**Comment by linzhouyu** [comment]
Please generate a test save by launching the game first. And use the test save to detect the Encryption ID, as documented in the Usage step 4 in README.

**Comment by PhinnTH** [comment]
Thanks! I'll try tommorow in my time zone.

**Comment by PhinnTH** [comment]
> Please generate a test save by launching the game first. And use the test save to detect the Encryption ID, as documented in the Usage step 4 in README.

How to generate test save. I dunno.

**Comment by linzhouyu** [comment]
As already mentioned, you can launch the game and create a save, and use it as test save.
Also, this is not the place for providing support. If you have more questions, feel free to send me an email. Issue will be closed.
