### ISSUE TITLE
Dear creator. Plz support AC Chronicles (Only China and Russia).

### ISSUE THREAD

**Issue by PhinnTH** [linzhouyu/ACST#24]
as a topic. Plz support AC Chronicles China and AC Chronicles Russia due to I lost the save in Chronicles China. Hope your tool support both game.
P.S. Why AC Chronicles India is later? Due to AC Chronicle India is the era that non-important history. But I don't mind if your tool support AC Chronicles India. Hope you do at your best. 😄

**Comment by linzhouyu** [comment]
AC Chronicles trilogy saves are not encrypted, means they could be use directly. There is no point for this tool to support it.
