### ISSUE TITLE
Hey, Linzhouyu! It's error from previous case my friend!

### ISSUE THREAD

**Issue by PhinnTH** [linzhouyu/ACST#25]
![Screenshot (309)](https://user-images.githubusercontent.com/38722732/79629621-4ced5380-8175-11ea-9973-408ed5db47c3.png)
![Screenshot (310)](https://user-images.githubusercontent.com/38722732/79629623-4f4fad80-8175-11ea-941c-a2d4a8206c61.png)
Here, I play in Uplay. So my save is encrypted. and I need to convert both save game due to save lost! Here's as following ; AC Chronicles China and AC Chronicles Russia. I didn't convert in AC Chronicles India. But however. Plz support AC Chronicles Trilogy saves which is meant single title one. Not Chronicles Trilogy bundle friends.
P.S. Sorry for disturb you my friend. Due to I play these game in Uplay and I can't find Uplay save.
![Screenshot (311)](https://user-images.githubusercontent.com/38722732/79629751-3b587b80-8176-11ea-8f4f-201403133cda.png)

**Comment by linzhouyu** [comment]
Already mentioned in #24, AC Chronicles trilogy saves are NOT encrypted. They could be shared between different accounts. Please don't open more issues about this.
