### ISSUE TITLE
Help! I can't convert AC Liberation HD saves!

### ISSUE THREAD

**Issue by PhinnTH** [linzhouyu/ACST#26]
![Screenshot (411)](https://user-images.githubusercontent.com/38722732/80600829-283b8a80-8a57-11ea-929b-a10e887eaf85.png)
Here's evidence... I can't convert AC Liberation HD Save! And I will tell you about AC Chronicles that saves are encryted. (Well, I've talking wit Ubisoft live chat support.) T^T
Here's summary that I need to convert AC Chronicles China saves and AC Chronicles Russia Saves...
[transcript.txt](https://github.com/linzhouyu/ACST/files/4551917/transcript.txt)
Hope you help me about AC Liberation HD. But I don't expect about AC Chronicles Trilogy... T^T

**Comment by PhinnTH** [comment]
> 
> 
> ![Screenshot (411)](https://user-images.githubusercontent.com/38722732/80600829-283b8a80-8a57-11ea-929b-a10e887eaf85.png)
> Here's evidence... I can't convert AC Liberation HD Save! And I will tell you about AC Chronicles that saves are encryted. (Well, I've talking wit Ubisoft live chat support.) T^T
> Here's summary that I need to convert AC Chronicles China saves and AC Chronicles Russia Saves...
> [transcript.txt](https://github.com/linzhouyu/ACST/files/4551917/transcript.txt)
> Hope you help me about AC Liberation HD. But I don't expect about AC Chronicles Trilogy... T^T

Don't forget to download transcript and read it please... It might help you not more or less... T^T

**Comment by linzhouyu** [comment]
1. This tool only supports legit Uplay format saves, not those non-standard save formats from unauthorized copy of games, which is most likely the case if you download saves from the Internet.
2. If you believe the AC Chronicles saves encrypted. Please send me an email with those saves so I could verify.
3. No offense, but this is NOT the place for providing support. Any further issues regarding this will be closed without notice.
