### ISSUE TITLE
Can't Start Program

### ISSUE THREAD

**Issue by decknine** [linzhouyu/ACST#3]
![capture](https://user-images.githubusercontent.com/42182450/51797343-866a3400-223c-11e9-8986-5541241b2127.PNG)

**Comment by linzhouyu** [comment]
This is an issue caused by 7zip sfx module and seems happen on a few machines. Cannot really reproduce it locally. Could you provide more details about your current system environment, like OS version, language settings, all installed VCredist versions. Thanks.
In the meantime, you could use this tool by extracting the packed exe manually with the latest 7-Zip.

**Comment by shma876** [comment]
The solution is to uninstall Winrar software

**Comment by decknine** [comment]
win 10 64bit, english language, VCredist 2005,08,10,12,13,17 X86 & 64.
I do not have winrar installed.
I have tried to manually extract only exe from .7zip, same result.

**Comment by linzhouyu** [comment]
@decknine  I have exact the same environment on my several test machines however couldn't repro the same issue. However I will try to tweak the 7zip sfx module settings to see it would fix the issue.
Btw, regarding manually extracting, I mean extract ACSaveTool_x64.exe itself using 7-Zip. After extraction you will have a ACST folder, run ACSaveTool.exe inside.

**Comment by linzhouyu** [comment]
@shma876  Did you have the same issue and fixed it by just uninstall WinRAR?

**Comment by shma876** [comment]
yes，I have same issue, even the error codes are same as the pictures he post. I have both winter and 7zip. After I uninstalled winrar, the problem solved.

**Comment by linzhouyu** [comment]
@shma876 Hum, that's weird. I also have these two software installed and it seems working fine. Could you kindly verify if you install the WinRAR again, the same issue would happen or not?

**Comment by linzhouyu** [comment]
Closed for now due to the lack of repro environment & issue related to 3rd party software.

**Comment by zues73307-ship-it** [comment]
<img width="228" height="244" alt="Image" src="https://github.com/user-attachments/assets/606d1c91-6375-4e31-a771-17d845c1daab" />                                 i have the same issue please help  @linuslin0
