### ISSUE TITLE
AC Unity 3DM

### ISSUE THREAD

**Issue by Jojoa9625** [linzhouyu/ACST#32]
Hello, 

I was trying to load 3Dm save game but it said "Failed to load save"

Is there any thing I am missing
Decryption ID: 3DMGAME
Encryption ID: My Account GUID

Thanks in advance,

**Comment by Jojoa9625** [comment]
I used the 3DM tool >>> Thanks

**Comment by darkneptune** [comment]
Can you help me with my AC savegames? Here: https://cloud.disroot.org/s/W2rJkpCEXJnSxaf

**Comment by Jojoa9625** [comment]
Unfortunately, the tool I found is for AC Unity, and there is one for Syndicate (ONLY 3DM saves), those saves you have ALI123 I thinks this tool can handle them , also you need the Account GUID or Game key according to encryption type.

**Comment by darkneptune** [comment]
I couldnt load these savedgames:
Assassin's Creed Liberation HD     // Game key
Assassin's Creed IV Black Flag     // Game key
Assassin's Creed III **Remastered**  // Account GUID
**Assassin's Creed Revelations       // Legacy username in lower case**
AC China

: _ _ _(

**Comment by darkneptune** [comment]
Hi,

Im trying to reuse my savedgame from Batman Arkham City from 2012, now into Epic Games Store. I tried a lot of things but nothing. I think your post could be the solution: Batman: Arkham City Save File Fixer/Patcher (Use your GFWL Savegame again) but i didnt found the link to download it.

Here is my savedgame if you need it: https://1drv.ms/u/s!Aiu4JVnrgR_ZsluMdqmFIexGL8dL?e=CWXSLG

Please help. :)

**Comment by JediRhymeTrix** [comment]
> Unfortunately, the tool I found is for AC Unity, and there is one for Syndicate (ONLY 3DM saves), those saves you have ALI123 I thinks this tool can handle them , also you need the Account GUID or Game key according to encryption type.

Hey, sorry to comment on a closed issue, but do you mind telling me where I can find the 3DM tool for Syndicate?
