### ISSUE TITLE
AC Revelations problem

### ISSUE THREAD

**Issue by Beelruce** [linzhouyu/ACST#36]
Whenever I want to use a converted save file, it says "damaged save file"
For the decryption ID, I put "revelationsaves" 
For the encryption ID, I put my legacy username in lower case form. After doing everything right, I still get damaged save file. Can you fix this?

**Comment by linzhouyu** [comment]
Hi there, please make sure the username used for decryption id is correct. Otherwise feel free to send me an email with your saves.

**Comment by Beelruce** [comment]
Hi,
This is the save file I am trying to convert. I used my legacy name
correctly for the encryption. The save file was downloaded from online and
the owner said the decryption code is revelationsaves.

**Comment by linzhouyu** [comment]
I didn't see the saves. Please send me an email directly.

**Comment by Beelruce** [comment]
I did send the save in the email directly. Do you see it now?

**Comment by Beelruce** [comment]
https://drive.google.com/file/d/1RzhB5sDBcy9gBwrM4Y4VXgfG0Ic8dg_T/view?usp=sharing

**Comment by linzhouyu** [comment]
I was able to decrypt this save using "revelationsaves" and converted to my own username, verified with my game copy and it could be loaded without issue. Seems like something wrong with your legacy username string used for re-encrypt the save.
If you never changed username before, the it would just be your current username.
Another thing is, are there any special character in your username?

**Comment by Beelruce** [comment]
It seems I was using my current username not my legacy username. I totally
forgot I changed my username a long time ago. Thank you so much. It works
now.
