### ISSUE TITLE
Assassin's Creed Black Flag

### ISSUE THREAD

**Issue by Beelruce** [linzhouyu/ACST#37]
I recently found out that ACSaveTool currently works for everything except Black Flag. It says the game key is required for black flag, but if you buy the standard edition of black flag, you don't get any key. Is there a fix for this? In the image below, it shows that AC Black Flag doesn't have a key. 
![Capture](https://user-images.githubusercontent.com/15662075/93030323-20d4e200-f5f0-11ea-9f56-c4ce582711e4.PNG)

**Comment by linzhouyu** [comment]
If you don't find a key for a certain game, try load a test save generated by that game on your account (there is a button on the right side of the encryption id textfield). This tool will then detect and use the same encryption ID to re-encrypt saves.

**Comment by Beelruce** [comment]
Thanks it worked.
