### ISSUE TITLE
Watch Dogs: Legion

### ISSUE THREAD

**Issue by Alekcan** [linzhouyu/ACST#39]
Is it possible to add convert saves for legion?

**Comment by linzhouyu** [comment]
Unfortunately it's not possible at least for now.

**Comment by oleedd** [comment]
What about Watch Dogs 2?

**Comment by linzhouyu** [comment]
> What about Watch Dogs 2?

WD2 saves are not encrypted.

**Comment by oleedd** [comment]
Good. So you can support it.

**Comment by linzhouyu** [comment]
> Good. So you can support it.

There is no need to "support" this, not encrypted means you could just use saves from other players.

**Comment by oleedd** [comment]
Cool. I didn't know that. Thanks.
Still no way for Legion?

**Comment by linzhouyu** [comment]
> Cool. I didn't know that. Thanks.
> Still no way for Legion?

I haven't got the chance to look at that yet. Currently there is no plan to add support to this tool since it's using a different encryption method.

**Comment by oleedd** [comment]
It would be awesome for many people if you cope with Legion in the future.

**Comment by oleedd** [comment]
What about Trials Rising?

**Comment by linzhouyu** [comment]
> What about Trials Rising?

Saves not encrypted as well. Please do not hijack this thread. If you have other questions feel free to send me an email.
