### ISSUE TITLE
Support for Ghost Recon Wildlands

### ISSUE THREAD

**Issue by cicalagg** [linzhouyu/ACST#4]
Hello,
I tried using this program to transfer the Ghost Recon Wildlands save files from one account to another, without success.

Any chance you could support Wildlands too? 
It probably uses the same system as Assassins Creed's

Game id is 1771 or 3559 depending if purchased on Steam or Uplay.

Thanks and great work!

**Comment by linzhouyu** [comment]
Hey there,
GRW saves are different. There is no plan to add support for it at this moment.

**Comment by cicalagg** [comment]
Hi again,
with my very basic reverse engineering skills I tried opening the save fine in an hex editor and I found that the first bytes contain the following text:

`A�C�4�B�F�[�9�]�-�t�m�_�2�0�1�9�_�0�2�_�2�2�_�2�2�_�0�7�_�4�1�`

AC4BF seemed to be referring to Assassin's Creed 4 Black Flag, so I tried using ACST setting Black Flag as game type, decryption id autodetect and my account's GUID as encryption id.

ACST successfully generated the converted files, but once loaded in Wildlands the game says the files are corrupted.

Are you sure GRW saves are that different from Assassins'?
Can you give me some hints so I can go ahead by myself trying decoding and reencoding the files? What's the encryption scheme?

Cheers!

**Comment by linzhouyu** [comment]
Yes, the save header does looks the same as AC4BF, however header info isn't always accurate if you check out saves from other titles.
Btw, this is not the right place for this kind of discussion, please feel free to shot me an email.
Thanks.
