### ISSUE TITLE
DetectS actualy work? (AcR)

### ISSUE THREAD

**Issue by mycop5** [linzhouyu/ACST#40]
Hello.
Because of hdd problem i lost my progress in ACR
I found good saves pack (you saw it at one of iisue)
However no matter i do i cant convert.

1.When i chose auto detect game after click convert it say   unknown title.
2. When i select detect decryption id it not found it.
3. When i select save file for encryption key it also say cant detect encryption key.

My first general question is detect optiion for AcR actualy work? And if yes how they do it? 
How can i find correct dec\enc key manualy? (at offline machine)

**Comment by linzhouyu** [comment]
ACR saves don't support any auto detection feature. You would need to know the old & new username as decryption & encryption ID in order to convert these saves.

**Comment by mycop5** [comment]
"ACR saves don't support any auto detection feature"
Even title?  
there is no information anywhere in the description
"You would need to know the old & new"
It is possible find correct user name at offline machine?

**Comment by linzhouyu** [comment]
As stated in the readme, auto detection only will work on certain game saves, ACR is just not one of them.
Readme also listed ACR should use legacy username as decryption & encryption ID.
You should know your own username to use as encryption ID. As the decryption ID for existing saves you want to convert, there is no straightforward way, feel free to send me an email with saves you want to convert and I will take a look. This is not a place to providing support.
