### ISSUE TITLE
ACST not work at windows 10 1803

### ISSUE THREAD

**Issue by mycop5** [linzhouyu/ACST#41]
After duble click anytime error apear
Application error:
Exception Code: 0x0000006ba
Adress: 0x95444a308
Exception data:
windows version 1803
Defender disabled.

**Comment by linzhouyu** [comment]
#3 
This might related to the OS environment (like VC Runtime) and/or 3rd party applications installed, the error came from self-extraction module.
Please try extract the exe directly and run the actual exe inside instead.

**Comment by mycop5** [comment]
Confirm. After extract it worked.
