### ISSUE TITLE
AC revelations transfer save to Theta or Skidrow viseversa

### ISSUE THREAD

**Issue by mycop5** [linzhouyu/ACST#42]
It is possible to transfer game progress to Theta or Skidrow version? And theta\skidrow to Uplay
I have problem with it.
As i understand ACST can detect if entered decryption key is incorrect. Else is just not decrypted.
so. i trying next.
1. i decrypt Theta with username theta and SKiDrow with skidrow. however i cant encrypt it with same names cuz game just even not see save. (not corrupted!)
2. I decrypt some saves from internet (you trying this files too....and you told that worked so..then i belive this files workes) and encrypt it with same theta\skidrow names. (lov case) Same problem. Game not see it.

Theta\Skidrow have they own special save files? But why then it decrypted fine?

**Comment by linzhouyu** [comment]
Those saves have slightly different/old save formats, they might be able to be loaded by ACST but ACST will only convert them to standard save format. Note that converted saves from this tool are only suppose to be used in legit copy of games.
