### ISSUE TITLE
Rainbow Support

### ISSUE THREAD

**Issue by Stage4000** [linzhouyu/ACST#48]
this would be pretty bad ass if you added support for rainbow 6 siege.

**Comment by linzhouyu** [comment]
I don't think r6 saves are encrypted. They only contain offline training mission progress (and probably some other minor stuffs) though, most other stuffs are recorded on the server.

**Comment by Stage4000** [comment]
They also contain your uniforms and gun skins which for some dumb reason isn't server checked.

**Comment by Stage4000** [comment]
You can unlock all the elite skins using only a save file that has them equipped to the character. I'd like to decrypt this and manipulate it manually instead of injecting an unlock all hack.

**Comment by linzhouyu** [comment]
Sorry I am not quite familiar with r6. If those data are being stored in 1.save then you should be able to use it directly since it's not encrypted.

**Comment by Stage4000** [comment]
Is it possible to make saves human readable? That's my goal, to manipulate the save directly.

**Comment by linzhouyu** [comment]
Not unless someone create a save editor for this game, which seems not that unnecessary for such a online game I would say.
