### ISSUE TITLE
Latest Immortals Fenyx Rising 1.11 (1.1.1) - Not working

### ISSUE THREAD

**Issue by GGLinnk** [linzhouyu/ACST#49]
Everything is in the title.

The tools doesn't work on the latest version of IFR (For me at least).

**Comment by linzhouyu** [comment]
Could you please send me a test save from 1.1.1 version of this game? Thanks.

**Comment by linzhouyu** [comment]
Resolved by email.

**Comment by LorenzoDelFa** [comment]
Hi, I have the same problem, how can I solve it?
