### ISSUE TITLE
Compatibility with Nintendo Switch saves

### ISSUE THREAD

**Issue by okruts** [linzhouyu/ACST#50]
Can you please make it compatible with Nintendo Switch saves (specifically Immortals Fenyx Rising)? It seems on switch we don't need Ubisoft account. I have tried to convert PC save to Switch without Encryption ID and remove start of the file (```2400 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000```) to look similar to switch save (start from ```acdb fe00 3600 0000 0200 0000 0600 0000```) but after transfer I see that save is corrupted. I have attached switch save 
[AutoSave01.zip](https://github.com/linzhouyu/ACST/files/6031423/AutoSave01.zip)

**Comment by linzhouyu** [comment]
If you already did this and couldn't load the save, then PC and NS saves might not be compatible after all, at least for this game. Not sure if it would be possible by editing some other bytes in the save tho.

**Comment by linzhouyu** [comment]
Close due to lack of updates. Please feel free to reopen if there is something new on this.
