### ISSUE TITLE
Can't get it to run...

### ISSUE THREAD

**Issue by Punt1971** [linzhouyu/ACST#52]
Windows 10 Pro 20H2, Ryzen 5800x

Briefly shows in task manager then closes. Gui doesn't show.

Thanks

**Comment by linzhouyu** [comment]
Please try extract the ACSaveTool_x64.exe and run the ACSaveTool.exe inside, thanks.

**Comment by Punt1971** [comment]
Same thing happens.

thanks

**Comment by linzhouyu** [comment]
Hum, couldn't really repro this. Could you please check if there is a crash dump located in '%LOCALAPPDATA%\CrashDumps'?

**Comment by Punt1971** [comment]
There are a few, how do I send them/it to you?

**Comment by linzhouyu** [comment]
Please send me an email (listed on my GitHub profile) with these crash dumps. Thanks.

**Comment by linzhouyu** [comment]
Crash could happen on platforms have Hardware-enforced Stack Protection enabled. As a temp workaround, disabled this in v2.4.3.

**Comment by linzhouyu** [comment]
Thanks again for reporting this issue.
