### ISSUE TITLE
Immortals Fenyx Rising. Game not view save file.

### ISSUE THREAD

**Issue by Baton34** [linzhouyu/ACST#53]
I am trying to convert save files from empress 1.1.1 version to uplay 1.1.1 version.
If Game is [Auto Detect] than ACST says "Game title: Unknown"
If Game is Immortals than ACST says "Unable to detect encryption key."
If I set encryption key manualy ACST says "Done" but the game ignore that files.

**Comment by Baton34** [comment]
My fault. Sorry.

**Comment by LorenzoDelFa** [comment]
Hi, @Baton34 how you resolve that?

**Comment by Baton34** [comment]
Its was stupid mistake by me. I copied files from backup folder, I dont know why :) But acst still did not recognize game and cant find encryption key. Only manual settings works.
