### ISSUE TITLE
ACBF Convert Savefile from Ubisoft Connect to Steam

### ISSUE THREAD

**Issue by Rustie3000** [linzhouyu/ACST#54]
I own both a Version of Uplay and Steam for the Game AC Black Flag, because i couldn't use DLCs on my Uplay Version for some reason so i bought the Game + DLCs on Steam.
On my Uplay Version i was very far in the game and now i want to continue this Playthrough on my Steam Version but i don't know how to get the required "Encryption ID" for your Program to Convert the Savefile from the Uplay Version to the Steam Version.

How do i manage to do this or is it even possible with the Software you created?

**Comment by linzhouyu** [comment]
The "Encryption ID" would be the game key for your Steam version of this game. If there was no such key assigned by Steam (likely the case), then grab a save generated from the Steam version to use as the test save. There is a button right side of the "Encryption ID" text field to do that.

**Comment by linzhouyu** [comment]
Close due to lack of response.
