### ISSUE TITLE
Lost all progress on AC unity..

### ISSUE THREAD

**Issue by Quinshoo** [linzhouyu/ACST#55]
I d like some help please. I lost all my progress on assassins creed unity its doesnt write corrupted just completely lost i run windows 10 btw and when i try to convert the files from .sav to .save using my id number it says Failed to load save.
I'm not a pc expert so i d like to help if you dont mind :)

**Comment by linzhouyu** [comment]
This tool doesn't support saves from non-legit game copies. If you want to convert them just send me an email.

**Comment by Quinshoo** [comment]
Yes plz I want to convert them I was very far ahead on the game downloaded a key from eneba and lost all my progress there was nothing there when I restarted it just made me start over from the beginning.

Στάλθηκε από την Αλληλογραφία<https://go.microsoft.com/fwlink/?LinkId=550986> για Windows 10

Από: Linus ***@***.***>
Αποστολή: Σάββατο, 20 Μαρτίου 2021 6:50 μμ
Προς: ***@***.***>
Κοιν.: ***@***.***>; ***@***.***>
Θέμα: Re: [linzhouyu/ACST] Lost all progress on AC unity.. (#55)


This tool doesn't support saves from non-legit game copies. If you want to convert them just send me an email.

**Comment by linzhouyu** [comment]
Please send me an email directly with saves you want to convert, you can find my email on the GitHub profile.

**Comment by Quinshoo** [comment]
Did you get it?

Στάλθηκε από την Αλληλογραφία<https://go.microsoft.com/fwlink/?LinkId=550986> για Windows 10

Από: Linus ***@***.***>
Αποστολή: Σάββατο, 20 Μαρτίου 2021 6:58 μμ
Προς: ***@***.***>
Κοιν.: ***@***.***>; ***@***.***>
Θέμα: Re: [linzhouyu/ACST] Lost all progress on AC unity.. (#55)


Please send me an email directly with saves you want to convert, you can find my email on the GitHub profile.
