### ISSUE TITLE
Unable to detect encryption key

### ISSUE THREAD

**Issue by kikka2411** [linzhouyu/ACST#56]
Cant detect ID from test save. 
My game is Dodi repack and the save files location is user/name/appdata/roaming/Theta/Orbit/40

**Comment by linzhouyu** [comment]
Auto detection is not supported for AC Revelations saves. Choose ACR and use theta as Encryption ID.

**Comment by kikka2411** [comment]
Evening, thanks for answering =) Ok I managed to create them , but they don't work. Game crashes with some strange error "context bar" or is empty. Trying with multiple save files downloaded from internet.
I just was trying to continue the game since my game crashed and my save got corrupted, but I guess I'll have to drop it and watch how it ends on youtube sadly =(

**Comment by linzhouyu** [comment]
If the game was able to recognize the converted save then this tool already done its work. The crash might caused by game file corruption. Closing the issue.
