### ISSUE TITLE
Failed to load save.

### ISSUE THREAD

**Issue by TomPham204** [linzhouyu/ACST#7]
![image](https://user-images.githubusercontent.com/46714051/56367523-97b15400-621f-11e9-96d8-16a81c789e29.png)
It says my old RLD! saves cannot be loaded. Can you please take a look at it? I'm trying to convert RLD saves to uplay saves.

**Comment by linzhouyu** [comment]
RLD saves (and also some other non-standard saves) are not supported.
Please shot me an email if you want to convert these saves. Thanks.
