### ISSUE TITLE
I am a newb and I can't seem to open the file?

### ISSUE THREAD

**Issue by kshep94** [linzhouyu/ACST#8]
Please help! I download the file but when I click on it it's only showing in Github's desktop as a repository, and for the life of me I cannot make it appear as the dialog box. I think I am missing something obvious but I know nothing about coding or github so I don't even know where to start googling it to find the correct answer.
This is what I see on the github desktop and in the download folder.
![Capture11111](https://user-images.githubusercontent.com/51012970/58375482-e8545500-7f21-11e9-8ef2-907f741e2c22.PNG)
![Capture111](https://user-images.githubusercontent.com/51012970/58375491-15086c80-7f22-11e9-8863-15443d7a56e6.PNG)
Thanks for helping and sorry if this is something simple I am missing.

**Comment by linzhouyu** [comment]
Hey there,

If you want to download the latest release, just go to
https://github.com/linzhouyu/ACST/releases and click to download
ACSaveTool_2.3.1.7z archive.
After you download it, unextract it using 7-Zip or WinRAR.

Thanks.
Linus

**Comment by kshep94** [comment]
Amazing thank you, I knew it was something simple! This tool is fantastic great work!
