### ISSUE TITLE
[AC Rogue] Corrupted save game file

### ISSUE THREAD

**Issue by JGeraldoLima** [linzhouyu/ACST#9]
Hi man, thank you for your effort on this tool in advance!

Everythings seems to be fine, as you can see in the attached print. But when I tried to open the game, it showed me only one save option with title "Corrupted save game" and offers me to delete it. Any ideia for what's is going on?

![image](https://user-images.githubusercontent.com/6726996/58919545-dda97500-8704-11e9-94bf-e33184f13887.png)

**Comment by JGeraldoLima** [comment]
BTW I installed [this version](https://www.skidrowreloaded.com/codex-assassins-creed-rogue/), and now I have original one on Steam.

**Comment by linzhouyu** [comment]
Hi there,

Please make sure you give the correct Encryption ID, for AC Rogue, the
encryption ID would be its game key. If you don't have a game key assigned,
then just try to load a test save from this game on your account to detect
the encryption ID. Thanks.

**Comment by JGeraldoLima** [comment]
Isn't this key starting with "d4" my encription ID?

![image](https://user-images.githubusercontent.com/6726996/58920579-3da21a80-8709-11e9-86ee-f72f675caa82.png)

**Comment by linzhouyu** [comment]
Not for this game, which uses game key instead. As noted in
https://github.com/linzhouyu/ACST/blob/master/README.md

**Comment by JGeraldoLima** [comment]
OMG it worked! Thank you so much, man!

**Comment by Quinshoo** [comment]
I d like some help please. I lost all my progress on assassins creed unity its doesnt write corrupted just completely lost i run windows 10 btw and when i try to convert the files from .sav to .save using my id number it says Failed to load save.
I'm not a pc expert so i d like to help if you dont mind :)
